version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: unless-stopped
    container_name: backend
    volumes:
      - ./.eslintrc.json:/.eslintrc.json
      - ./backend:/backend
      - ./backend/node_modules
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017
      - PORT=5000
    command: npm run dev

    
  mongo:
    image: mongo
    restart: unless-stopped
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - data-volume:/data/db


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: frontend
    volumes:
      - ./.eslintrc.json:/.eslintrc.json
      - ./frontend:/frontend
    depends_on:
      - backend
    command: npm start

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local

      
